### ISSUE TITLE
Create JSON file to accept pull from mentors

### ISSUE THREAD

**Issue by tsl143** [firefox-addons/mentor-map#1]
The input should be a JSON file which will be updated by mentors (via PRs).
We can roll out blog/post on social media, explaining mentors how to add themselves in the map.
This will remove overheads, all we need to do is review and merge their PR, and one of the criteria for being mentor should be knowledge of github :P

**Comment by viswanathamsantosh** [comment]
markerData.json is the json where we could add the mentors. I was wondering if we should add any other fields to the json object(place needs to be added). Any thoughts @iamVP7 @hellokarthic ?

**Comment by iamVP7** [comment]
Dp of mentor, can we ask for link or will use gravatar logic itself. 

And it's good to display mentors website link in Techspeaker we displayed mozillans profile

**Comment by tsl143** [comment]
Adding to that, mozillian/reps profile?

**Comment by iamVP7** [comment]
mozillian profile.. as all might not have reps

**Comment by viswanathamsantosh** [comment]
What do you think of this PR? https://github.com/firefox-addons/mentor-map/pull/3

**Comment by hellokarthic** [comment]
adding telegram handle might be useful too. 
@viswanathamsantosh  I just went through the PR. I guess this is pretty much good and sufficient.

**Comment by tsl143** [comment]
PR merged
