### ISSUE TITLE
Auto center map as per markers

### ISSUE THREAD

**Issue by tsl143** [firefox-addons/mentor-map#30]
Currently we have fixed map center and zoom, which can give vague results.
We need to auto center and auto zoom the map on first launch so as too see markers in current viewport.

We can use following.
https://stackoverflow.com/questions/17277686/leaflet-js-center-the-map-on-a-group-of-markers#answer-17278940

**Comment by MathMesquita** [comment]
I'm taking this one ! :D

**Comment by tsl143** [comment]
Closed by #34
