### ISSUE TITLE
Add title and favicon

### ISSUE THREAD

**Issue by tsl143** [firefox-addons/mentor-map#35]
We can use https://addons.cdn.mozilla.net/static/img/favicon.ico as favicon
and Title would be - `Firefox Webextensions mentors and events`

@viswanathamsantosh @iamVP7 @hellokarthic suggestions?

**Comment by hellokarthic** [comment]
@tsl143  https://addons.cdn.mozilla.net/static/img/favicon.ico?b=5fa7d1f9-59ef6e72

We shall use this latest favicon used in AMO.

**Comment by unluisco** [comment]
can I do this?

**Comment by rudr4x5h** [comment]
@tsl143 can I take this?

**Comment by tsl143** [comment]
Closed by #36 .
